### ISSUE TITLE
SRI hashes

### ISSUE THREAD

**Issue by ncfavier** [symphorien/vim-nixhash#7]
The `<M-h>` command should be aware of [SRI hashes](https://github.com/winterqt/rfcs/blob/sri-hashes/rfcs/0131-sri-hashes.md). For example, it could insert `sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=` (randomised) if the line looks like `hash = ...`.

**Comment by symphorien** [comment]
mmh autodetection looks error-prone, and beyond my vim/lua skills. what about another binding, `<M-s>` for example?

**Comment by ncfavier** [comment]
Sure

**Comment by symphorien** [comment]
done
